### PR TITLE
Feature/additional translation commands

### PR DESCRIPTION
**Pull request by dario-baumberger**
I use your plugin, thank you so far for your work. What I missed was that I can select the target language so that the statically saved one from the settings is not always used. So that I can choose something else. This resulted in the following.

I've added 3 new commands:

**Translate selection: to language**
The target language can be selected by suggestion modal. It is not always sufficient that the target language is taken from the static settings.

**Translate selection: From a language to another**
The source and target languages can be selected by suggestion modal. It is not always sufficient that the target language is taken from the static settings. The source language can be recognized automatically; if this is not enough, this command helps.

**Translate selection: To language and append to selection**
I still saw the open issue (https://github.com/friebetill/obsidian-deepl/issues/3) and that you don't have time. Since I have made changes, I have taken the liberty of adding this as well.

Thank you for checking the pull requests. If you have any questions, please do not hesitate to contact me.

### CODE REVIEW

**Comment by dario-baumberger** [comment]
While taking the pictures, I noticed an error, which I will change over the weekend. For the "from to modal", the fromLanguages must be taken into account, as the English languages (en-gb/en-us) are only accepted for the target language, I am currently using the toLanguages.

**Comment by dario-baumberger** [comment]
Solved the problem: https://github.com/dario-baumberger/obsidian-deepl/commit/0ed89d5d01264a2e5e55f214a41901ea480ef093

**Comment by friebetill** [comment]
Hi Dario,

Thank you so much for your contribution! I greatly appreciate the time and effort you’ve put into this. I reviewed your code, and I must say it’s both clean and concise. Great job! The feature enhancements you've introduced are thoughtful and certainly beneficial for more flexible language options.

I am ready to merge this pull request, but before proceeding, I want to ensure you’ve included all intended changes. Should I go ahead and merge it, or is there anything else you’d like to add or modify?

Edit: To be consistent, we should add descriptions for the new commandos in the plugin settings. Can you do that?

**Comment by dario-baumberger** [comment]
Thank you for your feedback. I'm glad you like my suggestions and the solutions.

As requested, I have added the descriptions of the commands (https://github.com/friebetill/obsidian-deepl/pull/4/commits/cdec3160fca89dff83302bbfbd50d7b60aa03439).

The descriptions in the settings tab look like this: 
image

You can see what the readme looks like here: https://github.com/dario-baumberger/obsidian-deepl/tree/feature/additional-translation-commands


From my side, I have no more open changes. You are welcome to merge it.

**Pull request merged**
